//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp1.ZWSMM_OBTENER_DESC_DEST {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="binding", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZmmfObtenerDescDestinatarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service() {
            this.Url = global::WindowsFormsApp1.Properties.Settings.Default.WindowsFormsApp1_ZWSMM_OBTENER_DESC_DEST_service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZmmfObtenerDescDestinatarioCompletedEventHandler ZmmfObtenerDescDestinatarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZmmfObtenerDescDestinatarioResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZmmfObtenerDescDestinatarioResponse ZmmfObtenerDescDestinatario([System.Xml.Serialization.XmlElementAttribute("ZmmfObtenerDescDestinatario", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZmmfObtenerDescDestinatario ZmmfObtenerDescDestinatario1) {
            object[] results = this.Invoke("ZmmfObtenerDescDestinatario", new object[] {
                        ZmmfObtenerDescDestinatario1});
            return ((ZmmfObtenerDescDestinatarioResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZmmfObtenerDescDestinatarioAsync(ZmmfObtenerDescDestinatario ZmmfObtenerDescDestinatario1) {
            this.ZmmfObtenerDescDestinatarioAsync(ZmmfObtenerDescDestinatario1, null);
        }
        
        /// <remarks/>
        public void ZmmfObtenerDescDestinatarioAsync(ZmmfObtenerDescDestinatario ZmmfObtenerDescDestinatario1, object userState) {
            if ((this.ZmmfObtenerDescDestinatarioOperationCompleted == null)) {
                this.ZmmfObtenerDescDestinatarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZmmfObtenerDescDestinatarioOperationCompleted);
            }
            this.InvokeAsync("ZmmfObtenerDescDestinatario", new object[] {
                        ZmmfObtenerDescDestinatario1}, this.ZmmfObtenerDescDestinatarioOperationCompleted, userState);
        }
        
        private void OnZmmfObtenerDescDestinatarioOperationCompleted(object arg) {
            if ((this.ZmmfObtenerDescDestinatarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZmmfObtenerDescDestinatarioCompleted(this, new ZmmfObtenerDescDestinatarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmfObtenerDescDestinatario {
        
        private string pDestinatarioField;
        
        private string pFechaultimadescargaField;
        
        private int pLimitField;
        
        private bool pLimitFieldSpecified;
        
        private int pRowsetField;
        
        private bool pRowsetFieldSpecified;
        
        private int pTipodescargaField;
        
        private bool pTipodescargaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PDestinatario {
            get {
                return this.pDestinatarioField;
            }
            set {
                this.pDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PFechaultimadescarga {
            get {
                return this.pFechaultimadescargaField;
            }
            set {
                this.pFechaultimadescargaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PLimit {
            get {
                return this.pLimitField;
            }
            set {
                this.pLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PLimitSpecified {
            get {
                return this.pLimitFieldSpecified;
            }
            set {
                this.pLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PRowset {
            get {
                return this.pRowsetField;
            }
            set {
                this.pRowsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PRowsetSpecified {
            get {
                return this.pRowsetFieldSpecified;
            }
            set {
                this.pRowsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PTipodescarga {
            get {
                return this.pTipodescargaField;
            }
            set {
                this.pTipodescargaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PTipodescargaSpecified {
            get {
                return this.pTipodescargaFieldSpecified;
            }
            set {
                this.pTipodescargaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmsGetItemsDescDest {
        
        private int idField;
        
        private string origenField;
        
        private int empidField;
        
        private string rutclienteField;
        
        private string destinatarioField;
        
        private string codigolistaField;
        
        private string codigoarticuloField;
        
        private decimal preciobaseField;
        
        private decimal descuentoField;
        
        private decimal montodesctoField;
        
        private decimal preciolistaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Empid {
            get {
                return this.empidField;
            }
            set {
                this.empidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rutcliente {
            get {
                return this.rutclienteField;
            }
            set {
                this.rutclienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigolista {
            get {
                return this.codigolistaField;
            }
            set {
                this.codigolistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigoarticulo {
            get {
                return this.codigoarticuloField;
            }
            set {
                this.codigoarticuloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Preciobase {
            get {
                return this.preciobaseField;
            }
            set {
                this.preciobaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Montodescto {
            get {
                return this.montodesctoField;
            }
            set {
                this.montodesctoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Preciolista {
            get {
                return this.preciolistaField;
            }
            set {
                this.preciolistaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmsGetDescDest {
        
        private int countField;
        
        private string resultadoField;
        
        private string resultadoDesField;
        
        private int resultadoCodigoField;
        
        private int limitField;
        
        private int rowsetField;
        
        private ZmmsGetItemsDescDest[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResultadoDes {
            get {
                return this.resultadoDesField;
            }
            set {
                this.resultadoDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ResultadoCodigo {
            get {
                return this.resultadoCodigoField;
            }
            set {
                this.resultadoCodigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Rowset {
            get {
                return this.rowsetField;
            }
            set {
                this.rowsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZmmsGetItemsDescDest[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmfObtenerDescDestinatarioResponse {
        
        private ZmmsGetDescDest weDescdestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZmmsGetDescDest WeDescdest {
            get {
                return this.weDescdestField;
            }
            set {
                this.weDescdestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ZmmfObtenerDescDestinatarioCompletedEventHandler(object sender, ZmmfObtenerDescDestinatarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZmmfObtenerDescDestinatarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZmmfObtenerDescDestinatarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZmmfObtenerDescDestinatarioResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZmmfObtenerDescDestinatarioResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591