//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp1.CREA_PEDIDO {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZMMF_DO_VA01SOAP", Namespace="http://www.minutoverde.cl/CreacionPedidoVentas/")]
    public partial class ZMMF_DO_VA01 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CallZMMF_DO_VA01OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZMMF_DO_VA01() {
            this.Url = global::WindowsFormsApp1.Properties.Settings.Default.WindowsFormsApp1_CREA_PEDIDO_ZMMF_DO_VA01;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CallZMMF_DO_VA01CompletedEventHandler CallZMMF_DO_VA01Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.minutosverde.cl/ZMMF_DO_VA01/ZMMF_DO_VA01", RequestElementName="ZMMF_DO_VA01", RequestNamespace="http://www.minutoverde.cl/CreacionPedidoVentas/", ResponseElementName="ZMMF_DO_VA01Response", ResponseNamespace="http://www.minutoverde.cl/CreacionPedidoVentas/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("WE_RESULT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZMMF_DO_VA01ResponseWE_RESULT CallZMMF_DO_VA01([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ZMMF_DO_VA01WA_DATOS WA_DATOS) {
            object[] results = this.Invoke("CallZMMF_DO_VA01", new object[] {
                        WA_DATOS});
            return ((ZMMF_DO_VA01ResponseWE_RESULT)(results[0]));
        }
        
        /// <remarks/>
        public void CallZMMF_DO_VA01Async(ZMMF_DO_VA01WA_DATOS WA_DATOS) {
            this.CallZMMF_DO_VA01Async(WA_DATOS, null);
        }
        
        /// <remarks/>
        public void CallZMMF_DO_VA01Async(ZMMF_DO_VA01WA_DATOS WA_DATOS, object userState) {
            if ((this.CallZMMF_DO_VA01OperationCompleted == null)) {
                this.CallZMMF_DO_VA01OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallZMMF_DO_VA01OperationCompleted);
            }
            this.InvokeAsync("CallZMMF_DO_VA01", new object[] {
                        WA_DATOS}, this.CallZMMF_DO_VA01OperationCompleted, userState);
        }
        
        private void OnCallZMMF_DO_VA01OperationCompleted(object arg) {
            if ((this.CallZMMF_DO_VA01Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallZMMF_DO_VA01Completed(this, new CallZMMF_DO_VA01CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.minutoverde.cl/CreacionPedidoVentas/")]
    public partial class ZMMF_DO_VA01WA_DATOS {
        
        private string oRIGENField;
        
        private string eMPIDField;
        
        private string dESTINATARIOField;
        
        private string fOLIOGPField;
        
        private string fECHAGENField;
        
        private string fECHAREQField;
        
        private string vENDEDORField;
        
        private string oBS1Field;
        
        private string oBS2Field;
        
        private string eSTADOField;
        
        private string nRODOCRELField;
        
        private string nROREFERENCIAField;
        
        private string fECHADIGField;
        
        private string dESCTOCABField;
        
        private string lPRECIOField;
        
        private ZMMF_DO_VA01WA_DATOSItem[] iTEMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORIGEN {
            get {
                return this.oRIGENField;
            }
            set {
                this.oRIGENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMPID {
            get {
                return this.eMPIDField;
            }
            set {
                this.eMPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESTINATARIO {
            get {
                return this.dESTINATARIOField;
            }
            set {
                this.dESTINATARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FOLIOGP {
            get {
                return this.fOLIOGPField;
            }
            set {
                this.fOLIOGPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHAGEN {
            get {
                return this.fECHAGENField;
            }
            set {
                this.fECHAGENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHAREQ {
            get {
                return this.fECHAREQField;
            }
            set {
                this.fECHAREQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VENDEDOR {
            get {
                return this.vENDEDORField;
            }
            set {
                this.vENDEDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBS1 {
            get {
                return this.oBS1Field;
            }
            set {
                this.oBS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBS2 {
            get {
                return this.oBS2Field;
            }
            set {
                this.oBS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NRODOCREL {
            get {
                return this.nRODOCRELField;
            }
            set {
                this.nRODOCRELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NROREFERENCIA {
            get {
                return this.nROREFERENCIAField;
            }
            set {
                this.nROREFERENCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHADIG {
            get {
                return this.fECHADIGField;
            }
            set {
                this.fECHADIGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESCTOCAB {
            get {
                return this.dESCTOCABField;
            }
            set {
                this.dESCTOCABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LPRECIO {
            get {
                return this.lPRECIOField;
            }
            set {
                this.lPRECIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMMF_DO_VA01WA_DATOSItem[] ITEMS {
            get {
                return this.iTEMSField;
            }
            set {
                this.iTEMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.minutoverde.cl/CreacionPedidoVentas/")]
    public partial class ZMMF_DO_VA01WA_DATOSItem {
        
        private string lINEAField;
        
        private string cODIGOARTICULOField;
        
        private string cANTIDADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LINEA {
            get {
                return this.lINEAField;
            }
            set {
                this.lINEAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODIGOARTICULO {
            get {
                return this.cODIGOARTICULOField;
            }
            set {
                this.cODIGOARTICULOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.minutoverde.cl/CreacionPedidoVentas/")]
    public partial class ZMMF_DO_VA01ResponseWE_RESULT {
        
        private string cOUNTField;
        
        private string rESULTADOField;
        
        private string rESULTADO_DESField;
        
        private string rESULTADO_CODIGOField;
        
        private string nROPEDIDOERPField;
        
        private string eSTADOPEDIDOERPField;
        
        private string oBSERVACIONESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COUNT {
            get {
                return this.cOUNTField;
            }
            set {
                this.cOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESULTADO_DES {
            get {
                return this.rESULTADO_DESField;
            }
            set {
                this.rESULTADO_DESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESULTADO_CODIGO {
            get {
                return this.rESULTADO_CODIGOField;
            }
            set {
                this.rESULTADO_CODIGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NROPEDIDOERP {
            get {
                return this.nROPEDIDOERPField;
            }
            set {
                this.nROPEDIDOERPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ESTADOPEDIDOERP {
            get {
                return this.eSTADOPEDIDOERPField;
            }
            set {
                this.eSTADOPEDIDOERPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBSERVACIONES {
            get {
                return this.oBSERVACIONESField;
            }
            set {
                this.oBSERVACIONESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CallZMMF_DO_VA01CompletedEventHandler(object sender, CallZMMF_DO_VA01CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallZMMF_DO_VA01CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallZMMF_DO_VA01CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZMMF_DO_VA01ResponseWE_RESULT Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZMMF_DO_VA01ResponseWE_RESULT)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591