//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp1.ZWSSD_GENERAR_PEDIDO {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="binding", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZMMF_DO_VA01OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service() {
            this.Url = global::WindowsFormsApp1.Properties.Settings.Default.WindowsFormsApp1_ZWSSD_GENERAR_PEDIDO_service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZMMF_DO_VA01CompletedEventHandler ZMMF_DO_VA01Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZMMF_DO_VA01Response", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZMMF_DO_VA01Response ZMMF_DO_VA01([System.Xml.Serialization.XmlElementAttribute("ZMMF_DO_VA01", Namespace="urn:sap-com:document:sap:rfc:functions")] ZMMF_DO_VA01 ZMMF_DO_VA011) {
            object[] results = this.Invoke("ZMMF_DO_VA01", new object[] {
                        ZMMF_DO_VA011});
            return ((ZMMF_DO_VA01Response)(results[0]));
        }
        
        /// <remarks/>
        public void ZMMF_DO_VA01Async(ZMMF_DO_VA01 ZMMF_DO_VA011) {
            this.ZMMF_DO_VA01Async(ZMMF_DO_VA011, null);
        }
        
        /// <remarks/>
        public void ZMMF_DO_VA01Async(ZMMF_DO_VA01 ZMMF_DO_VA011, object userState) {
            if ((this.ZMMF_DO_VA01OperationCompleted == null)) {
                this.ZMMF_DO_VA01OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZMMF_DO_VA01OperationCompleted);
            }
            this.InvokeAsync("ZMMF_DO_VA01", new object[] {
                        ZMMF_DO_VA011}, this.ZMMF_DO_VA01OperationCompleted, userState);
        }
        
        private void OnZMMF_DO_VA01OperationCompleted(object arg) {
            if ((this.ZMMF_DO_VA01Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZMMF_DO_VA01Completed(this, new ZMMF_DO_VA01CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMMF_DO_VA01 {
        
        private ZMMS_ORDERS wA_DATOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZMMS_ORDERS WA_DATOS {
            get {
                return this.wA_DATOSField;
            }
            set {
                this.wA_DATOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMMS_ORDERS {
        
        private string oRIGENField;
        
        private int eMPIDField;
        
        private string dESTINATARIOField;
        
        private string fOLIOGPField;
        
        private string fECHAGENField;
        
        private string fECHAREQField;
        
        private string vENDEDORField;
        
        private string oBS1Field;
        
        private string oBS2Field;
        
        private string eSTADOField;
        
        private string nRODOCRELField;
        
        private string nROREFERENCIAField;
        
        private string fECHADIGField;
        
        private string dESCTOCABField;
        
        private string lPRECIOField;
        
        private ZMMS_ITEMS_ORDERS[] iTEMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORIGEN {
            get {
                return this.oRIGENField;
            }
            set {
                this.oRIGENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int EMPID {
            get {
                return this.eMPIDField;
            }
            set {
                this.eMPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESTINATARIO {
            get {
                return this.dESTINATARIOField;
            }
            set {
                this.dESTINATARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FOLIOGP {
            get {
                return this.fOLIOGPField;
            }
            set {
                this.fOLIOGPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHAGEN {
            get {
                return this.fECHAGENField;
            }
            set {
                this.fECHAGENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHAREQ {
            get {
                return this.fECHAREQField;
            }
            set {
                this.fECHAREQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VENDEDOR {
            get {
                return this.vENDEDORField;
            }
            set {
                this.vENDEDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBS1 {
            get {
                return this.oBS1Field;
            }
            set {
                this.oBS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBS2 {
            get {
                return this.oBS2Field;
            }
            set {
                this.oBS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NRODOCREL {
            get {
                return this.nRODOCRELField;
            }
            set {
                this.nRODOCRELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NROREFERENCIA {
            get {
                return this.nROREFERENCIAField;
            }
            set {
                this.nROREFERENCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FECHADIG {
            get {
                return this.fECHADIGField;
            }
            set {
                this.fECHADIGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DESCTOCAB {
            get {
                return this.dESCTOCABField;
            }
            set {
                this.dESCTOCABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LPRECIO {
            get {
                return this.lPRECIOField;
            }
            set {
                this.lPRECIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMMS_ITEMS_ORDERS[] ITEMS {
            get {
                return this.iTEMSField;
            }
            set {
                this.iTEMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMMS_ITEMS_ORDERS {
        
        private string lINEAField;
        
        private string cODIGOARTICULOField;
        
        private decimal cANTIDADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LINEA {
            get {
                return this.lINEAField;
            }
            set {
                this.lINEAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODIGOARTICULO {
            get {
                return this.cODIGOARTICULOField;
            }
            set {
                this.cODIGOARTICULOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CANTIDAD {
            get {
                return this.cANTIDADField;
            }
            set {
                this.cANTIDADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMMS_RESULT_ORD {
        
        private int cOUNTField;
        
        private string rESULTADOField;
        
        private string rESULTADO_DESField;
        
        private int rESULTADO_CODIGOField;
        
        private string nROPEDIDOERPField;
        
        private string eSTADOPEDIDOERPField;
        
        private string oBSERVACIONESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int COUNT {
            get {
                return this.cOUNTField;
            }
            set {
                this.cOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESULTADO_DES {
            get {
                return this.rESULTADO_DESField;
            }
            set {
                this.rESULTADO_DESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RESULTADO_CODIGO {
            get {
                return this.rESULTADO_CODIGOField;
            }
            set {
                this.rESULTADO_CODIGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NROPEDIDOERP {
            get {
                return this.nROPEDIDOERPField;
            }
            set {
                this.nROPEDIDOERPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ESTADOPEDIDOERP {
            get {
                return this.eSTADOPEDIDOERPField;
            }
            set {
                this.eSTADOPEDIDOERPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBSERVACIONES {
            get {
                return this.oBSERVACIONESField;
            }
            set {
                this.oBSERVACIONESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMMF_DO_VA01Response {
        
        private ZMMS_RESULT_ORD wE_RESULTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZMMS_RESULT_ORD WE_RESULT {
            get {
                return this.wE_RESULTField;
            }
            set {
                this.wE_RESULTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ZMMF_DO_VA01CompletedEventHandler(object sender, ZMMF_DO_VA01CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZMMF_DO_VA01CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZMMF_DO_VA01CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZMMF_DO_VA01Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZMMF_DO_VA01Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591