//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hoffens.com:443/integracion/ws/hoffensServicio.php")]
        public string WindowsFormsApp1_WsHoffensV2_ServicioWebIntegracionEnexum {
            get {
                return ((string)(this["WindowsFormsApp1_WsHoffensV2_ServicioWebIntegracionEnexum"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sapqasp9.ayf.local:8000/sap/bc/srt/scs/sap/zwsmm_obtener_productos?sap-cli" +
            "ent=310")]
        public string WindowsFormsApp1_local_ayf_sapqasp9_service {
            get {
                return ((string)(this["WindowsFormsApp1_local_ayf_sapqasp9_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sapqasp9.ayf.local:8000/sap/bc/srt/scs/sap/zwsmm_obtener_desc_dest?sap-cli" +
            "ent=310")]
        public string WindowsFormsApp1_ZWSMM_OBTENER_DESC_DEST_service {
            get {
                return ((string)(this["WindowsFormsApp1_ZWSMM_OBTENER_DESC_DEST_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sapqasp9.ayf.local:8000/sap/bc/srt/scs/sap/zwsmm_obtener_clientes?sap-clie" +
            "nt=310")]
        public string WindowsFormsApp1_ZWSMM_OBTENER_CLIENTES_service {
            get {
                return ((string)(this["WindowsFormsApp1_ZWSMM_OBTENER_CLIENTES_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sapqasp9.ayf.local:8000/sap/bc/srt/scs/sap/zwssd_obtcli?sap-client=310")]
        public string WindowsFormsApp1_CLIENTES_service {
            get {
                return ((string)(this["WindowsFormsApp1_CLIENTES_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sapqasp9.ayf.local:8000/sap/bc/srt/scs/sap/zwssd_generar_pedido?sap-client" +
            "=310")]
        public string WindowsFormsApp1_ZWSSD_GENERAR_PEDIDO_service {
            get {
                return ((string)(this["WindowsFormsApp1_ZWSSD_GENERAR_PEDIDO_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://alifrutcpiprd.it-cpi019-rt.cfapps.us10-002.hana.ondemand.com/cxf/QAS/GetPo" +
            "int/CreacionPedidoVentas")]
        public string WindowsFormsApp1_CREA_PEDIDO_ZMMF_DO_VA01 {
            get {
                return ((string)(this["WindowsFormsApp1_CREA_PEDIDO_ZMMF_DO_VA01"]));
            }
        }
    }
}
