//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp1.WsHoffensV2 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioWebIntegracionEnexumBinding", Namespace="urn:servicioWebWSDL")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(articulo))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(orden))]
    public partial class ServicioWebIntegracionEnexum : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ordenesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioWebIntegracionEnexum() {
            this.Url = global::WindowsFormsApp1.Properties.Settings.Default.WindowsFormsApp1_WsHoffensV2_ServicioWebIntegracionEnexum;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ordenesCompletedEventHandler ordenesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:servicioWebWSDL#ordenes", RequestNamespace="urn:servicioWebWSDL", ResponseNamespace="urn:servicioWebWSDL")]
        [return: System.Xml.Serialization.SoapElementAttribute("codResult")]
        public string ordenes(string token, out orden[] listado_ordenes) {
            object[] results = this.Invoke("ordenes", new object[] {
                        token});
            listado_ordenes = ((orden[])(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ordenesAsync(string token) {
            this.ordenesAsync(token, null);
        }
        
        /// <remarks/>
        public void ordenesAsync(string token, object userState) {
            if ((this.ordenesOperationCompleted == null)) {
                this.ordenesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnordenesOperationCompleted);
            }
            this.InvokeAsync("ordenes", new object[] {
                        token}, this.ordenesOperationCompleted, userState);
        }
        
        private void OnordenesOperationCompleted(object arg) {
            if ((this.ordenesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ordenesCompleted(this, new ordenesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:servicioWebWSDL")]
    public partial class orden {
        
        private cliente clienteField;
        
        private general generalField;
        
        private direccionDespacho direccionDespachoField;
        
        private direccionPedido direccionPedidoField;
        
        private articulo[] listado_articulosField;
        
        /// <remarks/>
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        public general general {
            get {
                return this.generalField;
            }
            set {
                this.generalField = value;
            }
        }
        
        /// <remarks/>
        public direccionDespacho direccionDespacho {
            get {
                return this.direccionDespachoField;
            }
            set {
                this.direccionDespachoField = value;
            }
        }
        
        /// <remarks/>
        public direccionPedido direccionPedido {
            get {
                return this.direccionPedidoField;
            }
            set {
                this.direccionPedidoField = value;
            }
        }
        
        /// <remarks/>
        public articulo[] listado_articulos {
            get {
                return this.listado_articulosField;
            }
            set {
                this.listado_articulosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:servicioWebWSDL")]
    public partial class cliente {
        
        private string cardcodeField;
        
        private string nombreField;
        
        private string telefonoField;
        
        private string emailField;
        
        /// <remarks/>
        public string cardcode {
            get {
                return this.cardcodeField;
            }
            set {
                this.cardcodeField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:servicioWebWSDL")]
    public partial class articulo {
        
        private string skuField;
        
        private string precioField;
        
        private string cantidadField;
        
        /// <remarks/>
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
            }
        }
        
        /// <remarks/>
        public string precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <remarks/>
        public string cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:servicioWebWSDL")]
    public partial class direccionPedido {
        
        private string regionField;
        
        private string direccionField;
        
        private string sectorField;
        
        private string telefonoField;
        
        /// <remarks/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
            }
        }
        
        /// <remarks/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:servicioWebWSDL")]
    public partial class direccionDespacho {
        
        private string regionField;
        
        private string direccionField;
        
        private string sectorField;
        
        private string telefonoField;
        
        /// <remarks/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
            }
        }
        
        /// <remarks/>
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:servicioWebWSDL")]
    public partial class general {
        
        private string numeroField;
        
        private string tipoPagoField;
        
        private string medioPagoField;
        
        private string metodoEnvioField;
        
        private string montoEnvioField;
        
        private string comentarioClienteField;
        
        private string enviaDireccionTerceroField;
        
        private string direccionTerceroField;
        
        private string montoField;
        
        private string descuentoField;
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string tipoPago {
            get {
                return this.tipoPagoField;
            }
            set {
                this.tipoPagoField = value;
            }
        }
        
        /// <remarks/>
        public string medioPago {
            get {
                return this.medioPagoField;
            }
            set {
                this.medioPagoField = value;
            }
        }
        
        /// <remarks/>
        public string metodoEnvio {
            get {
                return this.metodoEnvioField;
            }
            set {
                this.metodoEnvioField = value;
            }
        }
        
        /// <remarks/>
        public string montoEnvio {
            get {
                return this.montoEnvioField;
            }
            set {
                this.montoEnvioField = value;
            }
        }
        
        /// <remarks/>
        public string comentarioCliente {
            get {
                return this.comentarioClienteField;
            }
            set {
                this.comentarioClienteField = value;
            }
        }
        
        /// <remarks/>
        public string enviaDireccionTercero {
            get {
                return this.enviaDireccionTerceroField;
            }
            set {
                this.enviaDireccionTerceroField = value;
            }
        }
        
        /// <remarks/>
        public string direccionTercero {
            get {
                return this.direccionTerceroField;
            }
            set {
                this.direccionTerceroField = value;
            }
        }
        
        /// <remarks/>
        public string monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ordenesCompletedEventHandler(object sender, ordenesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ordenesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ordenesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public orden[] listado_ordenes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((orden[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591