//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp1.local.ayf.sapqasp9 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="binding", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZmmfObtenerProductosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service() {
            this.Url = global::WindowsFormsApp1.Properties.Settings.Default.WindowsFormsApp1_local_ayf_sapqasp9_service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZmmfObtenerProductosCompletedEventHandler ZmmfObtenerProductosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZmmfObtenerProductosResponse", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
        public ZmmfObtenerProductosResponse ZmmfObtenerProductos([System.Xml.Serialization.XmlElementAttribute("ZmmfObtenerProductos", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")] ZmmfObtenerProductos ZmmfObtenerProductos1) {
            object[] results = this.Invoke("ZmmfObtenerProductos", new object[] {
                        ZmmfObtenerProductos1});
            return ((ZmmfObtenerProductosResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZmmfObtenerProductosAsync(ZmmfObtenerProductos ZmmfObtenerProductos1) {
            this.ZmmfObtenerProductosAsync(ZmmfObtenerProductos1, null);
        }
        
        /// <remarks/>
        public void ZmmfObtenerProductosAsync(ZmmfObtenerProductos ZmmfObtenerProductos1, object userState) {
            if ((this.ZmmfObtenerProductosOperationCompleted == null)) {
                this.ZmmfObtenerProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZmmfObtenerProductosOperationCompleted);
            }
            this.InvokeAsync("ZmmfObtenerProductos", new object[] {
                        ZmmfObtenerProductos1}, this.ZmmfObtenerProductosOperationCompleted, userState);
        }
        
        private void OnZmmfObtenerProductosOperationCompleted(object arg) {
            if ((this.ZmmfObtenerProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZmmfObtenerProductosCompleted(this, new ZmmfObtenerProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmfObtenerProductos {
        
        private string pFechaultimadescargaField;
        
        private int pLimitField;
        
        private bool pLimitFieldSpecified;
        
        private int pRowsetField;
        
        private bool pRowsetFieldSpecified;
        
        private int pTipodescargaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PFechaultimadescarga {
            get {
                return this.pFechaultimadescargaField;
            }
            set {
                this.pFechaultimadescargaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PLimit {
            get {
                return this.pLimitField;
            }
            set {
                this.pLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PLimitSpecified {
            get {
                return this.pLimitFieldSpecified;
            }
            set {
                this.pLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PRowset {
            get {
                return this.pRowsetField;
            }
            set {
                this.pRowsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PRowsetSpecified {
            get {
                return this.pRowsetFieldSpecified;
            }
            set {
                this.pRowsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PTipodescarga {
            get {
                return this.pTipodescargaField;
            }
            set {
                this.pTipodescargaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmsGetItemsProducts {
        
        private int idField;
        
        private string origenField;
        
        private int empidField;
        
        private string codigoarticuloField;
        
        private string descripartField;
        
        private string descriptecnicaField;
        
        private string descripcortaField;
        
        private string unidadmedidaField;
        
        private string lineaproductoField;
        
        private string tipomodeloField;
        
        private string versionField;
        
        private string origen1Field;
        
        private string rotacionField;
        
        private string codigofabricaField;
        
        private string marcaField;
        
        private int tipoField;
        
        private int usaserieField;
        
        private string unidadesempaqueField;
        
        private string ean13Field;
        
        private string dun14Field;
        
        private string vigenciadesdeField;
        
        private string vigenciahastaField;
        
        private string unidadmedidacompraField;
        
        private string unidadmedidaventaField;
        
        private string codigoproveedorField;
        
        private int bodegadefectoField;
        
        private string ubicaciondefectoField;
        
        private int ilaField;
        
        private string dato1Field;
        
        private string dato2Field;
        
        private decimal pesonetoField;
        
        private string bloqueomaterialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Empid {
            get {
                return this.empidField;
            }
            set {
                this.empidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigoarticulo {
            get {
                return this.codigoarticuloField;
            }
            set {
                this.codigoarticuloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descripart {
            get {
                return this.descripartField;
            }
            set {
                this.descripartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descriptecnica {
            get {
                return this.descriptecnicaField;
            }
            set {
                this.descriptecnicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descripcorta {
            get {
                return this.descripcortaField;
            }
            set {
                this.descripcortaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unidadmedida {
            get {
                return this.unidadmedidaField;
            }
            set {
                this.unidadmedidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lineaproducto {
            get {
                return this.lineaproductoField;
            }
            set {
                this.lineaproductoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Tipomodelo {
            get {
                return this.tipomodeloField;
            }
            set {
                this.tipomodeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Origen1 {
            get {
                return this.origen1Field;
            }
            set {
                this.origen1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rotacion {
            get {
                return this.rotacionField;
            }
            set {
                this.rotacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigofabrica {
            get {
                return this.codigofabricaField;
            }
            set {
                this.codigofabricaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Usaserie {
            get {
                return this.usaserieField;
            }
            set {
                this.usaserieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unidadesempaque {
            get {
                return this.unidadesempaqueField;
            }
            set {
                this.unidadesempaqueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ean13 {
            get {
                return this.ean13Field;
            }
            set {
                this.ean13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dun14 {
            get {
                return this.dun14Field;
            }
            set {
                this.dun14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vigenciadesde {
            get {
                return this.vigenciadesdeField;
            }
            set {
                this.vigenciadesdeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vigenciahasta {
            get {
                return this.vigenciahastaField;
            }
            set {
                this.vigenciahastaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unidadmedidacompra {
            get {
                return this.unidadmedidacompraField;
            }
            set {
                this.unidadmedidacompraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Unidadmedidaventa {
            get {
                return this.unidadmedidaventaField;
            }
            set {
                this.unidadmedidaventaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigoproveedor {
            get {
                return this.codigoproveedorField;
            }
            set {
                this.codigoproveedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Bodegadefecto {
            get {
                return this.bodegadefectoField;
            }
            set {
                this.bodegadefectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ubicaciondefecto {
            get {
                return this.ubicaciondefectoField;
            }
            set {
                this.ubicaciondefectoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Ila {
            get {
                return this.ilaField;
            }
            set {
                this.ilaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dato1 {
            get {
                return this.dato1Field;
            }
            set {
                this.dato1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dato2 {
            get {
                return this.dato2Field;
            }
            set {
                this.dato2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Pesoneto {
            get {
                return this.pesonetoField;
            }
            set {
                this.pesonetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bloqueomaterial {
            get {
                return this.bloqueomaterialField;
            }
            set {
                this.bloqueomaterialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmsGetProducts {
        
        private int countField;
        
        private string resultadoField;
        
        private string resultadoDesField;
        
        private int resultadoCodigoField;
        
        private int limitField;
        
        private int rowsetField;
        
        private ZmmsGetItemsProducts[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ResultadoDes {
            get {
                return this.resultadoDesField;
            }
            set {
                this.resultadoDesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ResultadoCodigo {
            get {
                return this.resultadoCodigoField;
            }
            set {
                this.resultadoCodigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Rowset {
            get {
                return this.rowsetField;
            }
            set {
                this.rowsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZmmsGetItemsProducts[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmfObtenerProductosResponse {
        
        private ZmmsGetProducts weProductsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZmmsGetProducts WeProducts {
            get {
                return this.weProductsField;
            }
            set {
                this.weProductsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ZmmfObtenerProductosCompletedEventHandler(object sender, ZmmfObtenerProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZmmfObtenerProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZmmfObtenerProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZmmfObtenerProductosResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZmmfObtenerProductosResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591