//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="ServiceReference1.ZWSMM_OBTENER_CLIENTES")]
    public interface ZWSMM_OBTENER_CLIENTES {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ZmmfObtenerClientes no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesResponse1 ZmmfObtenerClientes(WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesResponse1> ZmmfObtenerClientesAsync(WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmfObtenerClientes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pFechaultimadescargaField;
        
        private int pLimitField;
        
        private bool pLimitFieldSpecified;
        
        private int pRowsetField;
        
        private bool pRowsetFieldSpecified;
        
        private int pTipodescargaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string PFechaultimadescarga {
            get {
                return this.pFechaultimadescargaField;
            }
            set {
                this.pFechaultimadescargaField = value;
                this.RaisePropertyChanged("PFechaultimadescarga");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int PLimit {
            get {
                return this.pLimitField;
            }
            set {
                this.pLimitField = value;
                this.RaisePropertyChanged("PLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PLimitSpecified {
            get {
                return this.pLimitFieldSpecified;
            }
            set {
                this.pLimitFieldSpecified = value;
                this.RaisePropertyChanged("PLimitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int PRowset {
            get {
                return this.pRowsetField;
            }
            set {
                this.pRowsetField = value;
                this.RaisePropertyChanged("PRowset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PRowsetSpecified {
            get {
                return this.pRowsetFieldSpecified;
            }
            set {
                this.pRowsetFieldSpecified = value;
                this.RaisePropertyChanged("PRowsetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int PTipodescarga {
            get {
                return this.pTipodescargaField;
            }
            set {
                this.pTipodescargaField = value;
                this.RaisePropertyChanged("PTipodescarga");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmsGetItemsCustomers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string origenField;
        
        private int empidField;
        
        private string rutclienteField;
        
        private string nombresField;
        
        private string apellidosField;
        
        private string nombrefantasiaField;
        
        private string razonsocialField;
        
        private int giroField;
        
        private string tipoclienteField;
        
        private int sucursalField;
        
        private string nombresucursalField;
        
        private string direccionField;
        
        private string telefonoField;
        
        private string emailField;
        
        private string comunaField;
        
        private string ciuidField;
        
        private int regionField;
        
        private string contactoField;
        
        private string telefonocontactoField;
        
        private string tiporeferenciaField;
        
        private string numeroreferenciaField;
        
        private string codigoextField;
        
        private string codigolistaField;
        
        private string lineacreditoField;
        
        private string formapagoField;
        
        private int bancoField;
        
        private string nrocuentaField;
        
        private string vendedorField;
        
        private string georeferenciaField;
        
        private string indbloqueoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
                this.RaisePropertyChanged("Origen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int Empid {
            get {
                return this.empidField;
            }
            set {
                this.empidField = value;
                this.RaisePropertyChanged("Empid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Rutcliente {
            get {
                return this.rutclienteField;
            }
            set {
                this.rutclienteField = value;
                this.RaisePropertyChanged("Rutcliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("Nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("Apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Nombrefantasia {
            get {
                return this.nombrefantasiaField;
            }
            set {
                this.nombrefantasiaField = value;
                this.RaisePropertyChanged("Nombrefantasia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Razonsocial {
            get {
                return this.razonsocialField;
            }
            set {
                this.razonsocialField = value;
                this.RaisePropertyChanged("Razonsocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int Giro {
            get {
                return this.giroField;
            }
            set {
                this.giroField = value;
                this.RaisePropertyChanged("Giro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Tipocliente {
            get {
                return this.tipoclienteField;
            }
            set {
                this.tipoclienteField = value;
                this.RaisePropertyChanged("Tipocliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int Sucursal {
            get {
                return this.sucursalField;
            }
            set {
                this.sucursalField = value;
                this.RaisePropertyChanged("Sucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Nombresucursal {
            get {
                return this.nombresucursalField;
            }
            set {
                this.nombresucursalField = value;
                this.RaisePropertyChanged("Nombresucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Comuna {
            get {
                return this.comunaField;
            }
            set {
                this.comunaField = value;
                this.RaisePropertyChanged("Comuna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Ciuid {
            get {
                return this.ciuidField;
            }
            set {
                this.ciuidField = value;
                this.RaisePropertyChanged("Ciuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Contacto {
            get {
                return this.contactoField;
            }
            set {
                this.contactoField = value;
                this.RaisePropertyChanged("Contacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Telefonocontacto {
            get {
                return this.telefonocontactoField;
            }
            set {
                this.telefonocontactoField = value;
                this.RaisePropertyChanged("Telefonocontacto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Tiporeferencia {
            get {
                return this.tiporeferenciaField;
            }
            set {
                this.tiporeferenciaField = value;
                this.RaisePropertyChanged("Tiporeferencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string Numeroreferencia {
            get {
                return this.numeroreferenciaField;
            }
            set {
                this.numeroreferenciaField = value;
                this.RaisePropertyChanged("Numeroreferencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Codigoext {
            get {
                return this.codigoextField;
            }
            set {
                this.codigoextField = value;
                this.RaisePropertyChanged("Codigoext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string Codigolista {
            get {
                return this.codigolistaField;
            }
            set {
                this.codigolistaField = value;
                this.RaisePropertyChanged("Codigolista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string Lineacredito {
            get {
                return this.lineacreditoField;
            }
            set {
                this.lineacreditoField = value;
                this.RaisePropertyChanged("Lineacredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Formapago {
            get {
                return this.formapagoField;
            }
            set {
                this.formapagoField = value;
                this.RaisePropertyChanged("Formapago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public int Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
                this.RaisePropertyChanged("Banco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Nrocuenta {
            get {
                return this.nrocuentaField;
            }
            set {
                this.nrocuentaField = value;
                this.RaisePropertyChanged("Nrocuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string Vendedor {
            get {
                return this.vendedorField;
            }
            set {
                this.vendedorField = value;
                this.RaisePropertyChanged("Vendedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string Georeferencia {
            get {
                return this.georeferenciaField;
            }
            set {
                this.georeferenciaField = value;
                this.RaisePropertyChanged("Georeferencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Indbloqueo {
            get {
                return this.indbloqueoField;
            }
            set {
                this.indbloqueoField = value;
                this.RaisePropertyChanged("Indbloqueo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmsGetCustomers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int countField;
        
        private string resultadoField;
        
        private string resultadoDesField;
        
        private int resultadoCodigoField;
        
        private int limitField;
        
        private int rowsetField;
        
        private ZmmsGetItemsCustomers[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ResultadoDes {
            get {
                return this.resultadoDesField;
            }
            set {
                this.resultadoDesField = value;
                this.RaisePropertyChanged("ResultadoDes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int ResultadoCodigo {
            get {
                return this.resultadoCodigoField;
            }
            set {
                this.resultadoCodigoField = value;
                this.RaisePropertyChanged("ResultadoCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int Limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("Limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int Rowset {
            get {
                return this.rowsetField;
            }
            set {
                this.rowsetField = value;
                this.RaisePropertyChanged("Rowset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZmmsGetItemsCustomers[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZmmfObtenerClientesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZmmsGetCustomers weCustomersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZmmsGetCustomers WeCustomers {
            get {
                return this.weCustomersField;
            }
            set {
                this.weCustomersField = value;
                this.RaisePropertyChanged("WeCustomers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZmmfObtenerClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientes ZmmfObtenerClientes;
        
        public ZmmfObtenerClientesRequest() {
        }
        
        public ZmmfObtenerClientesRequest(WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientes ZmmfObtenerClientes) {
            this.ZmmfObtenerClientes = ZmmfObtenerClientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZmmfObtenerClientesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesResponse ZmmfObtenerClientesResponse;
        
        public ZmmfObtenerClientesResponse1() {
        }
        
        public ZmmfObtenerClientesResponse1(WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesResponse ZmmfObtenerClientesResponse) {
            this.ZmmfObtenerClientesResponse = ZmmfObtenerClientesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWSMM_OBTENER_CLIENTESChannel : WindowsFormsApp1.ServiceReference1.ZWSMM_OBTENER_CLIENTES, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWSMM_OBTENER_CLIENTESClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.ZWSMM_OBTENER_CLIENTES>, WindowsFormsApp1.ServiceReference1.ZWSMM_OBTENER_CLIENTES {
        
        public ZWSMM_OBTENER_CLIENTESClient() {
        }
        
        public ZWSMM_OBTENER_CLIENTESClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWSMM_OBTENER_CLIENTESClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWSMM_OBTENER_CLIENTESClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWSMM_OBTENER_CLIENTESClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesResponse1 WindowsFormsApp1.ServiceReference1.ZWSMM_OBTENER_CLIENTES.ZmmfObtenerClientes(WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesRequest request) {
            return base.Channel.ZmmfObtenerClientes(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesResponse ZmmfObtenerClientes(WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientes ZmmfObtenerClientes1) {
            WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesRequest inValue = new WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesRequest();
            inValue.ZmmfObtenerClientes = ZmmfObtenerClientes1;
            WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesResponse1 retVal = ((WindowsFormsApp1.ServiceReference1.ZWSMM_OBTENER_CLIENTES)(this)).ZmmfObtenerClientes(inValue);
            return retVal.ZmmfObtenerClientesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesResponse1> WindowsFormsApp1.ServiceReference1.ZWSMM_OBTENER_CLIENTES.ZmmfObtenerClientesAsync(WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesRequest request) {
            return base.Channel.ZmmfObtenerClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesResponse1> ZmmfObtenerClientesAsync(WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientes ZmmfObtenerClientes) {
            WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesRequest inValue = new WindowsFormsApp1.ServiceReference1.ZmmfObtenerClientesRequest();
            inValue.ZmmfObtenerClientes = ZmmfObtenerClientes;
            return ((WindowsFormsApp1.ServiceReference1.ZWSMM_OBTENER_CLIENTES)(this)).ZmmfObtenerClientesAsync(inValue);
        }
    }
}
