//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApp1.CLIENTES {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="binding", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZSDF_OBTCLIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service() {
            this.Url = global::WindowsFormsApp1.Properties.Settings.Default.WindowsFormsApp1_CLIENTES_service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZSDF_OBTCLICompletedEventHandler ZSDF_OBTCLICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZSDF_OBTCLIResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZSDF_OBTCLIResponse ZSDF_OBTCLI([System.Xml.Serialization.XmlElementAttribute("ZSDF_OBTCLI", Namespace="urn:sap-com:document:sap:rfc:functions")] ZSDF_OBTCLI ZSDF_OBTCLI1) {
            object[] results = this.Invoke("ZSDF_OBTCLI", new object[] {
                        ZSDF_OBTCLI1});
            return ((ZSDF_OBTCLIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZSDF_OBTCLIAsync(ZSDF_OBTCLI ZSDF_OBTCLI1) {
            this.ZSDF_OBTCLIAsync(ZSDF_OBTCLI1, null);
        }
        
        /// <remarks/>
        public void ZSDF_OBTCLIAsync(ZSDF_OBTCLI ZSDF_OBTCLI1, object userState) {
            if ((this.ZSDF_OBTCLIOperationCompleted == null)) {
                this.ZSDF_OBTCLIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZSDF_OBTCLIOperationCompleted);
            }
            this.InvokeAsync("ZSDF_OBTCLI", new object[] {
                        ZSDF_OBTCLI1}, this.ZSDF_OBTCLIOperationCompleted, userState);
        }
        
        private void OnZSDF_OBTCLIOperationCompleted(object arg) {
            if ((this.ZSDF_OBTCLICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZSDF_OBTCLICompleted(this, new ZSDF_OBTCLICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSDF_OBTCLI {
        
        private string p_FECHAULTIMADESCARGAField;
        
        private int p_LIMITField;
        
        private bool p_LIMITFieldSpecified;
        
        private int p_ROWSETField;
        
        private bool p_ROWSETFieldSpecified;
        
        private int p_TIPODESCARGAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string P_FECHAULTIMADESCARGA {
            get {
                return this.p_FECHAULTIMADESCARGAField;
            }
            set {
                this.p_FECHAULTIMADESCARGAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int P_LIMIT {
            get {
                return this.p_LIMITField;
            }
            set {
                this.p_LIMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_LIMITSpecified {
            get {
                return this.p_LIMITFieldSpecified;
            }
            set {
                this.p_LIMITFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int P_ROWSET {
            get {
                return this.p_ROWSETField;
            }
            set {
                this.p_ROWSETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_ROWSETSpecified {
            get {
                return this.p_ROWSETFieldSpecified;
            }
            set {
                this.p_ROWSETFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int P_TIPODESCARGA {
            get {
                return this.p_TIPODESCARGAField;
            }
            set {
                this.p_TIPODESCARGAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSDS_OBTCLI_ITEMS {
        
        private int idField;
        
        private string oRIGENField;
        
        private int eMPIDField;
        
        private string rUTCLIENTEField;
        
        private string nOMBRESField;
        
        private string aPELLIDOSField;
        
        private string nOMBREFANTASIAField;
        
        private string rAZONSOCIALField;
        
        private int gIROField;
        
        private string tIPOCLIENTEField;
        
        private int sUCURSALField;
        
        private string nOMBRESUCURSALField;
        
        private string dIRECCIONField;
        
        private string tELEFONOField;
        
        private string eMAILField;
        
        private string cOMUNAField;
        
        private string cIUIDField;
        
        private int rEGIONField;
        
        private string cONTACTOField;
        
        private string tELEFONOCONTACTOField;
        
        private string tIPOREFERENCIAField;
        
        private string nUMEROREFERENCIAField;
        
        private string cODIGOEXTField;
        
        private string cODIGOLISTAField;
        
        private string lINEACREDITOField;
        
        private string fORMAPAGOField;
        
        private int bANCOField;
        
        private string nROCUENTAField;
        
        private string vENDEDORField;
        
        private string gEOREFERENCIAField;
        
        private string iNDBLOQUEOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORIGEN {
            get {
                return this.oRIGENField;
            }
            set {
                this.oRIGENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int EMPID {
            get {
                return this.eMPIDField;
            }
            set {
                this.eMPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RUTCLIENTE {
            get {
                return this.rUTCLIENTEField;
            }
            set {
                this.rUTCLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOMBRES {
            get {
                return this.nOMBRESField;
            }
            set {
                this.nOMBRESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string APELLIDOS {
            get {
                return this.aPELLIDOSField;
            }
            set {
                this.aPELLIDOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOMBREFANTASIA {
            get {
                return this.nOMBREFANTASIAField;
            }
            set {
                this.nOMBREFANTASIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RAZONSOCIAL {
            get {
                return this.rAZONSOCIALField;
            }
            set {
                this.rAZONSOCIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int GIRO {
            get {
                return this.gIROField;
            }
            set {
                this.gIROField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPOCLIENTE {
            get {
                return this.tIPOCLIENTEField;
            }
            set {
                this.tIPOCLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SUCURSAL {
            get {
                return this.sUCURSALField;
            }
            set {
                this.sUCURSALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NOMBRESUCURSAL {
            get {
                return this.nOMBRESUCURSALField;
            }
            set {
                this.nOMBRESUCURSALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DIRECCION {
            get {
                return this.dIRECCIONField;
            }
            set {
                this.dIRECCIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELEFONO {
            get {
                return this.tELEFONOField;
            }
            set {
                this.tELEFONOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMUNA {
            get {
                return this.cOMUNAField;
            }
            set {
                this.cOMUNAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CIUID {
            get {
                return this.cIUIDField;
            }
            set {
                this.cIUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int REGION {
            get {
                return this.rEGIONField;
            }
            set {
                this.rEGIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTACTO {
            get {
                return this.cONTACTOField;
            }
            set {
                this.cONTACTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELEFONOCONTACTO {
            get {
                return this.tELEFONOCONTACTOField;
            }
            set {
                this.tELEFONOCONTACTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPOREFERENCIA {
            get {
                return this.tIPOREFERENCIAField;
            }
            set {
                this.tIPOREFERENCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUMEROREFERENCIA {
            get {
                return this.nUMEROREFERENCIAField;
            }
            set {
                this.nUMEROREFERENCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODIGOEXT {
            get {
                return this.cODIGOEXTField;
            }
            set {
                this.cODIGOEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CODIGOLISTA {
            get {
                return this.cODIGOLISTAField;
            }
            set {
                this.cODIGOLISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LINEACREDITO {
            get {
                return this.lINEACREDITOField;
            }
            set {
                this.lINEACREDITOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FORMAPAGO {
            get {
                return this.fORMAPAGOField;
            }
            set {
                this.fORMAPAGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int BANCO {
            get {
                return this.bANCOField;
            }
            set {
                this.bANCOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NROCUENTA {
            get {
                return this.nROCUENTAField;
            }
            set {
                this.nROCUENTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VENDEDOR {
            get {
                return this.vENDEDORField;
            }
            set {
                this.vENDEDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GEOREFERENCIA {
            get {
                return this.gEOREFERENCIAField;
            }
            set {
                this.gEOREFERENCIAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string INDBLOQUEO {
            get {
                return this.iNDBLOQUEOField;
            }
            set {
                this.iNDBLOQUEOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSDS_OBTCLI {
        
        private int cOUNTField;
        
        private string rESULTADOField;
        
        private string rESULTADO_DESField;
        
        private int rESULTADO_CODIGOField;
        
        private int lIMITField;
        
        private int rOWSETField;
        
        private ZSDS_OBTCLI_ITEMS[] iTEMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int COUNT {
            get {
                return this.cOUNTField;
            }
            set {
                this.cOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESULTADO {
            get {
                return this.rESULTADOField;
            }
            set {
                this.rESULTADOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RESULTADO_DES {
            get {
                return this.rESULTADO_DESField;
            }
            set {
                this.rESULTADO_DESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RESULTADO_CODIGO {
            get {
                return this.rESULTADO_CODIGOField;
            }
            set {
                this.rESULTADO_CODIGOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int LIMIT {
            get {
                return this.lIMITField;
            }
            set {
                this.lIMITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ROWSET {
            get {
                return this.rOWSETField;
            }
            set {
                this.rOWSETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSDS_OBTCLI_ITEMS[] ITEMS {
            get {
                return this.iTEMSField;
            }
            set {
                this.iTEMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSDF_OBTCLIResponse {
        
        private ZSDS_OBTCLI wE_CUSTOMERSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZSDS_OBTCLI WE_CUSTOMERS {
            get {
                return this.wE_CUSTOMERSField;
            }
            set {
                this.wE_CUSTOMERSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ZSDF_OBTCLICompletedEventHandler(object sender, ZSDF_OBTCLICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZSDF_OBTCLICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZSDF_OBTCLICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZSDF_OBTCLIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZSDF_OBTCLIResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591